/*  =========================================================================
    zrtf - ZRTF wrapper

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef __zrtf_library_H_INCLUDED__
#define __zrtf_library_H_INCLUDED__

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  ZRTF version macros for compile-time API detection

#define ZRTF_VERSION_MAJOR 1
#define ZRTF_VERSION_MINOR 0
#define ZRTF_VERSION_PATCH 0

#define ZRTF_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ZRTF_VERSION \
    ZRTF_MAKE_VERSION(ZRTF_VERSION_MAJOR, ZRTF_VERSION_MINOR, ZRTF_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBZRTF_STATIC
#       define ZRTF_EXPORT
#   elif defined LIBZRTF_EXPORTS
#       define ZRTF_EXPORT __declspec(dllexport)
#   else
#       define ZRTF_EXPORT __declspec(dllimport)
#   endif
#else
#   define ZRTF_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _chatty_t chatty_t;
#define CHATTY_T_DEFINED


//  Public API classes
#include "chatty.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
